# Digital Ocean App Platform Configuration for Vue.js Client
name: sellia-client

# Use static site deployment (recommended for frontend apps)
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: DevelopFer/sellia-client
    branch: main
  build_command: npm run build:prod
  output_dir: /dist
  environment_slug: node-js
  envs:
  - key: VITE_API_URL
    value: https://sellia-api-9ck6l.ondigitalocean.app/api
  - key: VITE_SOCKET_URL
    value: https://sellia-api-9ck6l.ondigitalocean.app
  - key: VITE_APP_TITLE
    value: Sellia Chat
  - key: VITE_NODE_ENV
    value: production