# Digital Ocean App Platform Configuration for Vue.js Client
name: sellia-client
services:
- name: web
  source_dir: /
  github:
    repo: DevelopFer/sellia-client
    branch: main
  build_command: npm run build:prod
  dockerfile_path: Dockerfile.production
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: https://sellia-api.ondigitalocean.app/api
  - key: VITE_SOCKET_URL
    value: https://sellia-api.ondigitalocean.app
  - key: VITE_APP_TITLE
    value: Sellia Chat
  - key: VITE_NODE_ENV
    value: production

# Static site configuration (alternative to dockerized deployment)
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: DevelopFer/sellia-client
    branch: main
  build_command: npm run build:prod
  output_dir: /dist
  environment_slug: node-js
  envs:
  - key: VITE_API_URL
    value: https://sellia-api.ondigitalocean.app/api
  - key: VITE_SOCKET_URL
    value: https://sellia-api.ondigitalocean.app
  - key: VITE_APP_TITLE
    value: Sellia Chat
  - key: VITE_NODE_ENV
    value: production